services:
 mariadb:
  container_name: web-mariadb-13
  hostname: mariadb
  image: mariadb:10.5
  restart: always
  environment:
   MARIADB_ROOT_PASSWORD: password
   MARIADB_DATABASE: webdb
   MARIADB_USER: webdb
   MARIADB_PASSWORD: password
  ports:
   - "0.0.0.0:5113:3306"

 web:
  container_name: web-app-calculator-13
  hostname: app
  build: .
  ports:
   - "0.0.0.0:5013:5013"
